name: 'CTF Time'
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 5"

jobs:
    ctf-time-to-discord:
        runs-on: ubuntu-latest
        steps:
            - name: install dependencies
              run: |
                sudo apt update && sudo apt install jq nodejs npm -y;
                sudo npm install -g prettier;

            - name: get info via ctftime api
              run: |
               START=$(date -u +%s);
               END=$(date -u +%s -d "+7 days");
               curl -s "https://ctftime.org/api/v1/events/?limit=10&start=$START&end=$END" |jq > out.txt;
              shell: bash

            - name: send message via discord webhook
              shell: bash
              env:
                DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
              run: |
                LENGTH=$(jq length out.txt)
                LENGTH=$((LENGTH - 1))
                FIELDS=""

                for i in $(seq 0 $LENGTH); do
                    TITLE=$(jq -r ".[$i].title" out.txt)
                    START_TIME_RAW=$(jq -r ".[$i].start" out.txt)
                    START_TIME=$(TZ=Asia/Kolkata date -d "$START_TIME_RAW" +"%d-%m-%Y %H:%M")
                    URL=$(jq -r ".[$i].ctftime_url" out.txt)
                    WEIGHT=$(jq -r ".[$i].weight" out.txt)
                    FORMAT=$(jq -r ".[$i].format" out.txt)

                    if (( $(echo "$WEIGHT > 0" | bc -l) )); then
                        VALUE=$(printf "**Weight:** %s\n**Start:** %s\n[Link](%s)\n**Format:** %s" \
                                     "$WEIGHT" "$START_TIME" "$URL" "$FORMAT")

                        FIELD=$(jq -n \
                            --arg name "$TITLE" \
                            --arg value "$VALUE" \
                            '{name: $name, value: $value, inline: false}')

                        if [ -z "$FIELDS" ]; then
                            FIELDS="$FIELD"
                        else
                            FIELDS="$FIELDS,$FIELD"
                        fi
                    fi
                done

                PAYLOAD=$(jq -n \
                    --arg title "📅 Upcoming CTFs (Next 7 days)" \
                    --argjson fields "[$FIELDS]" \
                    '{embeds: [{title: $title, fields: $fields, color: 3447003}]}')

                curl -X POST "$DISCORD_WEBHOOK_URL" \
                     -H "Content-Type: application/json" \
                     -d "$PAYLOAD"
